// Generated by lsc from arrayEquals.ts

method arrayEquals(a: seq<string>, b: seq<string>) returns (res: bool)
  ensures ((res == true) ==> (|a| == |b|))
  ensures ((res == true) ==> forall k: nat :: ((k < |a|) ==> (a[k] == b[k])))
  ensures ((res == false) ==> (|a| == |b|) ==> exists k: nat :: ((k < |a|) && (a[k] != b[k])))
{
  var aLen := |a|;
  var bLen := |b|;
  if (aLen != bLen) {
    return false;
  }
  var result := true;
  var i := 0;
  while (i < aLen)
    invariant (i <= aLen)
    invariant ((result == true) ==> forall k: nat :: ((k < i) ==> (a[k] == b[k])))
    invariant ((result == false) ==> exists k: nat :: ((k < aLen) && (a[k] != b[k])))
    decreases (aLen - i)
  {
    if (a[i] != b[i]) {
      result := false;
      break;
    }
    i := (i + 1);
  }
  return result;
}
