/-
  Generated by lsc from arrayEquals.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import LemmaScript

set_option velvet.semantics.termination "total"

method arrayEquals (a : Array String) (b : Array String) returns (res : Bool)
  ensures ensures_1: (res = true → a.size = b.size : Prop)
  ensures ensures_2: (res = true → ∀ k : Nat, k < a.size → a[k]! = b[k]! : Prop)
  ensures ensures_3: (res = false → a.size = b.size → ∃ k : Nat, k < a.size ∧ a[k]! ≠ b[k]! : Prop)
  do
    let aLen := a.size
    let bLen := b.size
    if aLen ≠ bLen then
      return false
    let mut result : Bool := true
    let mut i : Nat := 0
    while i < aLen
      invariant invariant_1: (i ≤ aLen : Prop)
      invariant invariant_2: (result = true → ∀ k : Nat, k < i → a[k]! = b[k]! : Prop)
      invariant invariant_3: (result = false → ∃ k : Nat, k < aLen ∧ a[k]! ≠ b[k]! : Prop)
      decreasing aLen - i
      done_with (result = false ∨ ¬(i < aLen) : Prop)
    do
      if a[i]! ≠ b[i]! then
        result := false
        break
      i := i + 1
    return result
