/-
  Generated by lsc from arrayEquals.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import LemmaScript

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method arrayEquals (a : Array String) (b : Array String) return (res : Bool)
  ensures res = true → a.size = b.size
  ensures res = true → ∀ k : Nat, k < a.size → a[k]! = b[k]!
  ensures res = false → a.size = b.size → ∃ k : Nat, k < a.size ∧ a[k]! ≠ b[k]!
  do
    let aLen := a.size
    let bLen := b.size
    if aLen ≠ bLen then
      return false
    let mut result : Bool := true
    let mut i : Nat := 0
    while i < aLen
      invariant i ≤ aLen
      invariant result = true → ∀ k : Nat, k < i → a[k]! = b[k]!
      invariant result = false → ∃ k : Nat, k < aLen ∧ a[k]! ≠ b[k]!
      done_with result = false ∨ ¬(i < aLen)
      decreasing aLen - i
    do
      if a[i]! ≠ b[i]! then
        result := false
        break
      i := i + 1
    return result
