/-
  Generated by lsc from keyGet.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «keyGet.types»
import LemmaScript.JSString

set_option velvet.semantics.termination "total"

method keyGet (key1 : String) (key2 : String) returns (res : String)
  ensures ensures_1: (JSString.indexOf key2 "*" = -1 → res = "" : Prop)
  ensures ensures_2: (key1.length ≤ JSString.indexOf key2 "*" → res = "" : Prop)
  ensures ensures_3: (JSString.indexOf key2 "*" ≥ 0 → JSString.indexOf key2 "*" ≤ key1.length → JSString.indexOf key2 "*" ≤ key2.length → JSString.slice key1 0 (JSString.indexOf key2 "*") ≠ JSString.slice key2 0 (JSString.indexOf key2 "*") → res = "" : Prop)
  do
    return Pure.keyGet key1 key2
