// Generated by lsc from keyGet.ts

function StringIndexOf(s: string, sub: string): int
{
  StringIndexOfFrom(s, sub, 0)
}

function StringIndexOfFrom(s: string, sub: string, from: nat): int
  decreases |s| - from
{
  if from + |sub| > |s| then -1
  else if s[from..from + |sub|] == sub then from as int
  else StringIndexOfFrom(s, sub, from + 1)
}

lemma StringIndexOfBounds(s: string, sub: string)
  requires |sub| > 0
  ensures StringIndexOf(s, sub) == -1 || (0 <= StringIndexOf(s, sub) < |s|)
{
  StringIndexOfFromBounds(s, sub, 0);
}

lemma StringIndexOfFromBounds(s: string, sub: string, from: nat)
  requires |sub| > 0
  ensures StringIndexOfFrom(s, sub, from) == -1 || (from <= StringIndexOfFrom(s, sub, from) < |s|)
  decreases |s| - from
{
  if from + |sub| > |s| { }
  else if s[from..from + |sub|] == sub { assert from + |sub| <= |s|; }
  else { StringIndexOfFromBounds(s, sub, from + 1); }
}

function keyGet(key1: string, key2: string): string
{
  var pos := StringIndexOf(key2, "*");
  StringIndexOfBounds(key2, "*");
  if (pos == -1) then
    ""
  else
    if (|key1| > pos) then
      if (key1[0..pos] == key2[0..pos]) then
        key1[pos..|key1|]
      else
        ""
    else
      ""
}

lemma keyGet_ensures(key1: string, key2: string)
  ensures ((StringIndexOf(key2, "*") == -1) ==> (keyGet(key1, key2) == ""))
  ensures ((|key1| <= StringIndexOf(key2, "*")) ==> (keyGet(key1, key2) == ""))
  ensures ((StringIndexOf(key2, "*") >= 0) ==> (StringIndexOf(key2, "*") <= |key1|) ==> (StringIndexOf(key2, "*") <= |key2|) ==> (key1[0..StringIndexOf(key2, "*")] != key2[0..StringIndexOf(key2, "*")]) ==> (keyGet(key1, key2) == ""))
{
}
