/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript
import LemmaScript.JSString

namespace Pure

def keyGet (key1 : String) (key2 : String) : String :=
  let pos := JSString.indexOf key2 "*"
  if pos = -1 then
    ""
  else
    if key1.length > pos then
      if JSString.slice key1 0 pos = JSString.slice key2 0 pos then
        JSString.slice key1 pos key1.length
      else
        ""
    else
      ""

end Pure
