/-
  Generated by lsc from keyGet.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «keyGet.types»
import LemmaScript.JSString

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method keyGet (key1 : String) (key2 : String) return (res : String)
  ensures JSString.indexOf key2 "*" = -1 → res = ""
  ensures key1.length ≤ JSString.indexOf key2 "*" → res = ""
  ensures JSString.indexOf key2 "*" ≥ 0 → JSString.indexOf key2 "*" ≤ key1.length → JSString.indexOf key2 "*" ≤ key2.length → JSString.slice key1 0 (JSString.indexOf key2 "*") ≠ JSString.slice key2 0 (JSString.indexOf key2 "*") → res = ""
  do
    return Pure.keyGet key1 key2
