// Generated by lsc from keyGet.ts

function StringIndexOf(s: string, sub: string): int
  ensures StringIndexOf(s, sub) == -1
       || (0 <= StringIndexOf(s, sub) <= |s| - |sub| && s[StringIndexOf(s, sub)..StringIndexOf(s, sub) + |sub|] == sub)
{
  StringIndexOfFrom(s, sub, 0)
}

function StringIndexOfFrom(s: string, sub: string, from: int): int
  ensures StringIndexOfFrom(s, sub, from) == -1
       || (0 <= StringIndexOfFrom(s, sub, from) <= |s| - |sub|
           && s[StringIndexOfFrom(s, sub, from)..StringIndexOfFrom(s, sub, from) + |sub|] == sub
           && StringIndexOfFrom(s, sub, from) >= from)
{
  StringIndexOfFromN(s, sub, if from < 0 then 0 else from)
}

function StringIndexOfFromN(s: string, sub: string, from: nat): int
  decreases |s| - from
  ensures StringIndexOfFromN(s, sub, from) == -1
       || (from <= StringIndexOfFromN(s, sub, from) <= |s| - |sub|
           && s[StringIndexOfFromN(s, sub, from)..StringIndexOfFromN(s, sub, from) + |sub|] == sub)
{
  if from + |sub| > |s| then -1
  else if s[from..from + |sub|] == sub then from as int
  else StringIndexOfFromN(s, sub, from + 1)
}

function keyGet(key1: string, key2: string): string
{
  var pos := StringIndexOf(key2, "*");
  if (pos == -1) then
    ""
  else
    if (|key1| > pos) then
      if (key1[0..pos] == key2[0..pos]) then
        key1[pos..|key1|]
      else
        ""
    else
      ""
}

lemma keyGet_ensures(key1: string, key2: string)
  ensures ((StringIndexOf(key2, "*") == -1) ==> (keyGet(key1, key2) == ""))
  ensures ((|key1| <= StringIndexOf(key2, "*")) ==> (keyGet(key1, key2) == ""))
  ensures ((StringIndexOf(key2, "*") >= 0) ==> (StringIndexOf(key2, "*") <= |key1|) ==> (StringIndexOf(key2, "*") <= |key2|) ==> (key1[0..StringIndexOf(key2, "*")] != key2[0..StringIndexOf(key2, "*")]) ==> (keyGet(key1, key2) == ""))
{
}
