/-
  Generated by lsc from keyMatch.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «keyMatch.types»

set_option velvet.semantics.termination "total"

method keyMatch (key1 : String) (key2 : String) returns (res : Bool)
  ensures ensures_1: (key1 = key2 → res = true : Prop)
  do
    return Pure.keyMatch key1 key2
