/-
  Generated by lsc from keyMatch.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «keyMatch.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method keyMatch (key1 : String) (key2 : String) return (res : Bool)
  ensures key1 = key2 → res = true
  do
    return Pure.keyMatch key1 key2
