/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript
import LemmaScript.JSString

namespace Pure

def keyMatch (key1 : String) (key2 : String) : Bool :=
  let pos := JSString.indexOf key2 "*"
  if pos = -1 then
    key1 = key2
  else
    if key1.length > pos then
      JSString.slice key1 0 pos = JSString.slice key2 0 pos
    else
      key1 = JSString.slice key2 0 pos

end Pure
