// Generated by lsc from keyMatch.ts

function StringIndexOf(s: string, sub: string): int
  ensures StringIndexOf(s, sub) == -1 || (0 <= StringIndexOf(s, sub) <= |s| - |sub|)
{
  StringIndexOfFrom(s, sub, 0)
}

function StringIndexOfFrom(s: string, sub: string, from: nat): int
  ensures StringIndexOfFrom(s, sub, from) == -1 || (from <= StringIndexOfFrom(s, sub, from) <= |s| - |sub|)
  decreases |s| - from
{
  if from + |sub| > |s| then -1
  else if s[from..from + |sub|] == sub then from as int
  else StringIndexOfFrom(s, sub, from + 1)
}

function keyMatch(key1: string, key2: string): bool
{
  var pos := StringIndexOf(key2, "*");
  if (pos == -1) then
    (key1 == key2)
  else
    if (|key1| > pos) then
      (key1[0..pos] == key2[0..pos])
    else
      (key1 == key2[0..pos])
}

lemma keyMatch_ensures(key1: string, key2: string)
  ensures ((key1 == key2) ==> (keyMatch(key1, key2) == true))
{
}
