/-
  Generated by lsc from getFilteredPolicy.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import LemmaScript

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method ruleMatches (rule : Array String) (fieldValues : Array String) (fieldIndex : Nat) (numFields : Nat) return (res : Bool)
  require numFields ≤ fieldValues.size
  require fieldIndex + numFields ≤ rule.size
  ensures res = false → ∃ k : Nat, k < numFields ∧ fieldValues[k]! ≠ "" ∧ rule[fieldIndex + k]! ≠ fieldValues[k]!
  ensures res = true → ∀ k : Nat, k < numFields → fieldValues[k]! = "" ∨ rule[fieldIndex + k]! = fieldValues[k]!
  do
    let mut matched : Bool := true
    let mut i : Nat := 0
    while i < numFields
      invariant i ≤ numFields
      invariant matched = true → ∀ k : Nat, k < i → fieldValues[k]! = "" ∨ rule[fieldIndex + k]! = fieldValues[k]!
      invariant matched = false → ∃ k : Nat, k < numFields ∧ fieldValues[k]! ≠ "" ∧ rule[fieldIndex + k]! ≠ fieldValues[k]!
      done_with matched = false ∨ ¬(i < numFields)
      decreasing numFields - i
    do
      if fieldValues[i]! ≠ "" then
        if rule[fieldIndex + i]! ≠ fieldValues[i]! then
          matched := false
          break
      i := i + 1
    return matched

method filterPolicies (policies : Array (Array String)) (fieldValues : Array String) (fieldIndex : Nat) (numPolicies : Nat) (numFields : Nat) return (res : Array (Array String))
  require numPolicies ≤ policies.size
  require numFields ≤ fieldValues.size
  require ∀ i : Nat, i < numPolicies → fieldIndex + numFields ≤ (policies[i]!).size
  do
    let mut result : Array (Array String) := #[]
    let mut i : Nat := 0
    while i < numPolicies
      invariant i ≤ numPolicies
      decreasing numPolicies - i
    do
      let _t0 ← ruleMatches policies[i]! fieldValues fieldIndex numFields
      if _t0 then
        result := result ++ #[policies[i]!]
      i := i + 1
    return result
