// Generated by lsc from getFilteredPolicy.ts

method ruleMatches(rule: seq<string>, fieldValues: seq<string>, fieldIndex: nat, numFields: nat) returns (res: bool)
  requires (numFields <= |fieldValues|)
  requires ((fieldIndex + numFields) <= |rule|)
  ensures ((res == false) ==> exists k: nat :: (((k < numFields) && (fieldValues[k] != "")) && (rule[(fieldIndex + k)] != fieldValues[k])))
  ensures ((res == true) ==> forall k: nat :: ((k < numFields) ==> ((fieldValues[k] == "") || (rule[(fieldIndex + k)] == fieldValues[k]))))
{
  var matched := true;
  var i := 0;
  while (i < numFields)
    invariant (i <= numFields)
    invariant ((matched == true) ==> forall k: nat :: ((k < i) ==> ((fieldValues[k] == "") || (rule[(fieldIndex + k)] == fieldValues[k]))))
    invariant ((matched == false) ==> exists k: nat :: (((k < numFields) && (fieldValues[k] != "")) && (rule[(fieldIndex + k)] != fieldValues[k])))
    decreases (numFields - i)
  {
    if (fieldValues[i] != "") {
      if (rule[(fieldIndex + i)] != fieldValues[i]) {
        matched := false;
        break;
      }
    }
    i := (i + 1);
  }
  return matched;
}

method filterPolicies(policies: seq<seq<string>>, fieldValues: seq<string>, fieldIndex: nat, numPolicies: nat, numFields: nat) returns (res: seq<seq<string>>)
  requires (numPolicies <= |policies|)
  requires (numFields <= |fieldValues|)
  requires forall i: nat :: ((i < numPolicies) ==> ((fieldIndex + numFields) <= |policies[i]|))
{
  var result := [];
  var i := 0;
  while (i < numPolicies)
    invariant (i <= numPolicies)
    decreases (numPolicies - i)
  {
    var i_t0 := ruleMatches(policies[i], fieldValues, fieldIndex, numFields);
    if i_t0 {
      result := (result + [policies[i]]);
    }
    i := (i + 1);
  }
  return result;
}
