// Generated by lsc from effectorPure.ts

datatype Mode = allow | deny | allow_and_deny | priority

datatype Eft = allow | deny | indeterminate

datatype EffectState = EffectState(res: bool, recorded: bool, done: bool)

function pushEffectStep(mode: Mode, eft: Eft, state: EffectState): EffectState
{
  if state.done then
    state
  else
    if (mode == Mode.allow) then
      if (eft == Eft.allow) then
        EffectState(true, true, true)
      else
        EffectState(state.res, false, false)
    else
      if (mode == Mode.deny) then
        if (eft == Eft.deny) then
          EffectState(false, true, true)
        else
          EffectState(true, false, false)
      else
        if (mode == Mode.allow_and_deny) then
          if (eft == Eft.allow) then
            EffectState(true, true, false)
          else
            if (eft == Eft.deny) then
              EffectState(false, true, true)
            else
              EffectState(state.res, false, false)
        else
          if (eft != Eft.indeterminate) then
            EffectState((eft == Eft.allow), true, true)
          else
            EffectState(state.res, false, false)
}

method processEffects(mode: Mode, effects: seq<Eft>) returns (res: EffectState)
{
  var state := EffectState(false, false, false);
  var i := 0;
  while (i < |effects|)
    invariant (i <= |effects|)
    invariant ((mode == Mode.allow) ==> (state.done == true) ==> (state.res == true))
    invariant ((mode == Mode.deny) ==> (state.done == true) ==> (state.res == false))
    decreases (|effects| - i)
  {
    state := pushEffectStep(mode, effects[i], state);
    i := (i + 1);
  }
  return state;
}
