// Generated by lsc from effectorPure.ts

datatype Mode = allow | deny | allow_and_deny | priority

datatype Eft = allow | deny | indeterminate

datatype EffectState = EffectState(res: bool, recorded: bool, done: bool)

function pushEffectStep(mode: Mode, eft: Eft, state: EffectState): EffectState
{
  if state.done then
    state
  else
    if mode.allow? then
      if eft.allow? then
        EffectState(true, true, true)
      else
        EffectState(state.res, false, false)
    else
      if mode.deny? then
        if eft.deny? then
          EffectState(false, true, true)
        else
          EffectState(true, false, false)
      else
        if mode.allow_and_deny? then
          if eft.allow? then
            EffectState(true, true, false)
          else
            if eft.deny? then
              EffectState(false, true, true)
            else
              EffectState(state.res, false, false)
        else
          if (!eft.indeterminate?) then
            EffectState(eft.allow?, true, true)
          else
            EffectState(state.res, false, false)
}

lemma pushEffectStep_ensures(mode: Mode, eft: Eft, state: EffectState)
  ensures ((state.done == true) ==> (pushEffectStep(mode, eft, state) == state))
  ensures ((state.done == false) ==> mode.allow? ==> eft.allow? ==> ((pushEffectStep(mode, eft, state).res == true) && (pushEffectStep(mode, eft, state).done == true)))
  ensures ((state.done == false) ==> mode.deny? ==> eft.deny? ==> ((pushEffectStep(mode, eft, state).res == false) && (pushEffectStep(mode, eft, state).done == true)))
  ensures ((state.done == false) ==> mode.priority? ==> (!eft.indeterminate?) ==> (pushEffectStep(mode, eft, state).done == true))
  ensures ((state.done == false) ==> mode.priority? ==> eft.allow? ==> (pushEffectStep(mode, eft, state).res == true))
  ensures ((state.done == false) ==> mode.priority? ==> eft.deny? ==> (pushEffectStep(mode, eft, state).res == false))
  ensures ((state.done == false) ==> mode.allow? ==> (!eft.allow?) ==> (pushEffectStep(mode, eft, state).done == false))
  ensures ((state.done == false) ==> mode.deny? ==> (!eft.deny?) ==> (pushEffectStep(mode, eft, state).done == false))
{
}

method processEffects(mode: Mode, effects: seq<Eft>) returns (res: EffectState)
{
  var state := EffectState(false, false, false);
  var i := 0;
  while (i < |effects|)
    invariant (i <= |effects|)
    invariant (mode.allow? ==> (state.done == true) ==> (state.res == true))
    invariant (mode.deny? ==> (state.done == true) ==> (state.res == false))
    decreases (|effects| - i)
  {
    state := pushEffectStep(mode, effects[i], state);
    i := (i + 1);
  }
  return state;
}
