/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

inductive Mode where
  | allow : Mode
  | deny : Mode
  | allow_and_deny : Mode
  | priority : Mode
deriving Repr, Inhabited, DecidableEq

inductive Eft where
  | allow : Eft
  | deny : Eft
  | indeterminate : Eft
deriving Repr, Inhabited, DecidableEq

structure EffectState where
  res : Bool
  recorded : Bool
  done : Bool
deriving Repr, Inhabited, DecidableEq

namespace Pure

def pushEffectStep (mode : Mode) (eft : Eft) (state : EffectState) : EffectState :=
  if state.done then
    state
  else
    if mode = .allow then
      if eft = .allow then
        { res := true, recorded := true, done := true }
      else
        { res := state.res, recorded := false, done := false }
    else
      if mode = .deny then
        if eft = .deny then
          { res := false, recorded := true, done := true }
        else
          { res := true, recorded := false, done := false }
      else
        if mode = .allow_and_deny then
          if eft = .allow then
            { res := true, recorded := true, done := false }
          else
            if eft = .deny then
              { res := false, recorded := true, done := true }
            else
              { res := state.res, recorded := false, done := false }
        else
          if eft ≠ .indeterminate then
            { res := eft = .allow, recorded := true, done := true }
          else
            { res := state.res, recorded := false, done := false }

end Pure
