/-
  Generated by lsc from effectorPure.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «effectorPure.spec»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method pushEffectStep (mode : Mode) (eft : Eft) (state : EffectState) return (res : EffectState)
  ensures state.done = true → res = state
  ensures state.done = false → mode = Mode.allow → eft = Eft.allow → res.res = true ∧ res.done = true
  ensures state.done = false → mode = Mode.deny → eft = Eft.deny → res.res = false ∧ res.done = true
  ensures state.done = false → mode = Mode.priority → eft ≠ Eft.indeterminate → res.done = true
  ensures state.done = false → mode = Mode.priority → eft = Eft.allow → res.res = true
  ensures state.done = false → mode = Mode.priority → eft = Eft.deny → res.res = false
  ensures state.done = false → mode = Mode.allow → eft ≠ Eft.allow → res.done = false
  ensures state.done = false → mode = Mode.deny → eft ≠ Eft.deny → res.done = false
  do
    return Pure.pushEffectStep mode eft state

method processEffects (mode : Mode) (effects : Array Eft) return (res : EffectState)
  do
    let mut state : EffectState := { res := false, recorded := false, done := false }
    let mut i : Nat := 0
    while i < effects.size
      invariant i ≤ effects.size
      invariant mode = Mode.allow → state.done = true → state.res = true
      invariant mode = Mode.deny → state.done = true → state.res = false
      decreasing effects.size - i
    do
      state ← pushEffectStep mode effects[i]! state
      i := i + 1
    return state
